model:
  arch: video_llama
  model_type: pretrain_llama_v2

  llama_model: "meta-llama/Llama-2-7b-hf"
  ckpt: "/DANTE-AD/checkpoints/model-ckpt.pth.tar"
  # ckpt_2: "/DANTE-AD/checkpoints/ad3_moviellama2_ce_iter14000.pth.tar"
  equip_audio_branch: False


datasets:
  cmd_AD:
    vis_processor:
      train:
        name: "alpro_video_eval"
        n_frms: 8
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: video_text_pretrain