model:
  arch: video_llama
  model_type: pretrain_llama_v2

  # If you want use LLaMA-2-chat,
  # some ckpts could be download from our provided huggingface repo
  # i.e.  https://huggingface.co/DAMO-NLP-SG/Video-LLaMA-2-13B-Finetuned
  llama_model: "meta-llama/Llama-2-7b-hf"
  ckpt: "/PATH/TO/YOUR/CKPT"
  ckpt_2: ""  # Optional
  equip_audio_branch: False


datasets:
  cmd_AD:
    text_processor:
      train:
        name: "blip_caption"

run:
  task: video_text_pretrain