datasets:
  cmd_AD:
    data_type: video
    build_info:
      val_anno_dir: waves_eval.tsv
      train_anno_dir: waves_eval.tsv
      s4v_features: features/s4v_features/
      video_qformer_ft: features/10sFeatures/
      videos_dir: clips/
