datasets:
  cmd_AD:
    data_type: video
    build_info:
      val_anno_dir: data/ownfeatures/eval.tsv
      train_anno_dir: data/ownfeatures/eval.tsv
      s4v_features: data/ownfeatures/s4v/
      video_qformer_ft: data/ownfeatures/video_qformer_features/
